### ISSUE TITLE
404-s under kc60

### ISSUE THREAD

**Issue by zosiu** [qmk/qmk.fm_old#1]
I was trying to access keymaps from here: http://qmk.fm/keyboards/kc60/ :
- [default](http://qmk.fm/keyboards/kc60/keymaps/default/) -> 404
- [sgoodwin](http://qmk.fm/keyboards/kc60/keymaps/sgoodwin/) -> 404
- [workman-dead](http://qmk.fm/keyboards/kc60/keymaps/workman-dead/) -> 404
- [wiggunoi](http://qmk.fm/keyboards/kc60/keymaps/wigguno/) -> OK
- [stanleylai](http://qmk.fm/keyboards/kc60/keymaps/stanleylai/) -> OK
- [ws2812](http://qmk.fm/keyboards/kc60/keymaps/ws2812/) -> OK

**Comment by jackhumbert** [comment]
Yeah, they'll only show if they have `readme.md`s (they get converted to html files automatically).

**Comment by zosiu** [comment]
Hm, this does have a README.md : 

https://github.com/jackhumbert/qmk_firmware/tree/master/keyboards/kc60/keymaps/workman-dead

EDIT: seems like the readme.md has to be all lowercase for the conversion to work.
