### ISSUE TITLE
 handwired/dactyl_lightcycle is missing

### ISSUE THREAD

**Issue by manolodeinternet** [qmk/qmk.fm_old#10]
Hi guys !!!, handwired/dactyl_lightcycle is missing from the list. dactyl and dactyl/manuform are in the list, but the version of the dactyl with 4 rows x 6 columns and 5 thumb keys per hand is missing.
Thanks !!!

**Comment by drashna** [comment]
IIRC, the list is actually dynamically generated from the QMK Firmware repo every time a commit is added to the master branch there.  

So if it's missing, then it's most likely because it's not in the QMK Firmware repo.
