### ISSUE TITLE
Add the Kyria as a Powered by QMK keyboard

### ISSUE THREAD

**Issue by splitkb** [qmk/qmk.fm_old#103]
I'd be interested in having the Kyria featured as one of the keyboards that's supported by QMK. What are the steps I can undertake to make that happen?

**Comment by noroadsleft** [comment]
In short, comply with the guidelines given on https://qmk.fm/powered/:

- Don’t imply QMK or its contributors endorse/make the keyboard
- Contribute their keyboard’s configuration back to `qmk:master` roughly by the keyboard’s ship date
  **You've already done this, so you're good there.**
- Link to the QMK website (https://qmk.fm/) or Github repo (https://github.com/qmk/qmk_firmware) on their product page
  https://splitkb.com/collections/keyboard-kits/products/kyria-pcb-kit doesn't do this, but I imagine that should be easy enough to fix.

Your PR to add Kyria to the main list (I'm assuming that's what you're after) should edit:

- Each `index.md` file under https://github.com/qmk/qmk.fm/tree/gh-pages/_i18n (add Kyria to the list)
- **OPTIONAL** Create a `kyria.md` file in https://github.com/qmk/qmk.fm/tree/gh-pages/_i18n/en/keyboards
