### ISSUE TITLE
Help with keymapping RK61 Keyboard

### ISSUE THREAD

**Issue by Wexull** [qmk/qmk.fm_old#106]
New to coding, so got a starter mechanical keyboard, however a lot of the keys I need to use are either really poorly placed or don't exist on the keyboard (backslash for example).

I would LOVE to remap smoother features and a full key set, if it wasn't for the poor software that comes with the RK61 (That doesn't work for my non-RGB version) then this keyboard would be a perfect startup keyboard!

Could anyone help me with this so I can make full use of QMK? Thanks!

**Comment by marcovirtual** [comment]
I also have a keyboard by Royal Kludge (model RK71) and would like to know if it could be added to the QMK firmware.

**Comment by jloh02** [comment]
Based on [this article](https://www.techpowerup.com/review/royal-kludge-rk84-keyboard/4.html) the RK84 uses the BYK916 MCU. Unfortunately, there isn't much information about the PCB nor the MCU. If someone is able to find the schematics for this PCB/MCU (which is also used by the Feker PCBs), it'll definitely be easier to write the firmware.

**Comment by 0xYuzko** [comment]
Here you go. I'm not too knowledgeable in this sort of thing but I hope this can help someone.
https://github.com/0xYuzko/RK61-PCB

**Comment by qinyuhang** [comment]
The is a PR for rk71, I believe we can ref to it
[rk71 draft](https://github.com/Ernold11/qmk_firmware/pull/1)
