### ISSUE TITLE
replace gratipay with liberapay

### ISSUE THREAD

**Issue by davidak** [qmk/qmk.fm_old#11]
Gratipay has shut down.

https://gratipay.news/the-end-cbfba8f50981

There is a fork, Liberapay. Gratipay has hand their asset's over to them.

I also use Liberapay sucessfully, so i can reccommend that!

That will fix this broken link on your website: https://gratipay.com/QMK/

**Comment by drashna** [comment]
I think this has been resolved already, and can be closed @jackhumbert
