### ISSUE TITLE
KLE to convertion QMK fails

### ISSUE THREAD

**Issue by Supermagnum** [qmk/qmk.fm_old#111]
How I discovered the bug 
I pasted the  raw data from http://www.keyboard-layout-editor.com/#/gists/2fea0143064790fed378761bfa7f5600
  in to  https://qmk.fm/converter/ 
I tried to upload the result in to https://config.qmk.fm , but I get this error message

Sorry, this doesn't appear to be a QMK keymap file.

I had to rename the *.json file to *.txt to make attachment possible.

[info.txt](https://github.com/qmk/qmk.fm/files/5207995/info.txt)

**Comment by yanfali** [comment]
Seems to work just fine. I suspect you are using the wrong workflow.

1. paste raw into top box
2. convert
3. copy json into a info.json file

You cannot load this into the configurator using the import keymap mode, there is a special development mode (CTRL + SHIFT + I) in that order to load and preview info.json files. These are not the same as default keyboard keymaps, they are the internal physical mapping files the configurator uses for layouts.

I just tested your KLE and it worked for me.

[test.json.zip](https://github.com/qmk/qmk.fm/files/5210319/test.json.zip)
