### ISSUE TITLE
I've done goofed - qmk.fm isn't building properly after my commit.

### ISSUE THREAD

**Issue by FilipParyz** [qmk/qmk.fm_old#115]
Hi! After my commit which included Polish translations, GitHub Pages isn't able to build the repo.
I'm not sure what went wrong yet, but I hope I can fix it or at least learn what I did wrong.
@noroadsleft or @drashna , could you help me understand what's wrong?
![obraz](https://user-images.githubusercontent.com/10086191/96172901-5d656780-0f27-11eb-993b-7d9f9e2ea827.png)

**Comment by noroadsleft** [comment]
This is the error it's throwing:

![image](https://user-images.githubusercontent.com/18669334/96186540-6b4bc600-0ef0-11eb-96c6-c0d3efc3239d.png)

But that doesn't make sense to me because you didn't change anything in `/_layouts/` or `/_includes/`. :confused:

**Comment by noroadsleft** [comment]
Only thing I see different about your translation is the `/_i18n/pl/ChangeLog` file – I'm going to delete it and see what happens.

**Comment by noroadsleft** [comment]
Huh, no change in build.

**Comment by FilipParyz** [comment]
> But that doesn't make sense to me because you didn't change anything in /_layouts/ or /_includes/.

I know right? I'm not sure what I did wrong, but it's clearly my commit that broke it. I don't see any changes other than those with translation.

**Comment by FilipParyz** [comment]
Hey @jackhumbert , want to take a look?
