### ISSUE TITLE
QMK Support

### ISSUE THREAD

**Issue by licwang2008** [qmk/qmk.fm_old#124]
Dear Sir:
               I am sales director from Westberry, an chip maker company.
               We want to support QMK and contribute our code like STM32F103/303
               Could you help to tell me what's steps in detail.

               BR

               Lee Wang

**Comment by tzarc** [comment]
If MCUs like the WB32F103X are binary-compatible with STM32F103xx, then it might not require any modification at all.
If they're not compatible, you'd need to add support for your families of MCU to https://github.com/ChibiOS/ChibiOS-Contrib.
See the QMK documentation here: https://docs.qmk.fm/#/platformdev_selecting_arm_mcu
