### ISSUE TITLE
Idobao Montex Pad missing

### ISSUE THREAD

**Issue by snow-monkeys** [qmk/qmk.fm_old#130]
Can’t find it anywhere

**Comment by iso-hexane** [comment]
Anyone know anything about this? The board was supposed to ship with qmk and via support but I can't find either.

**Comment by NachoxMacho** [comment]
I've gotten a version working in qmk. It's not official but it works: https://github.com/qmk/qmk_firmware/pull/13214

**Comment by IBNobody** [comment]
@NachoxMacho Does your Montex V1 have full per-key RGB lighting? I wonder if I have a V2 because your build only lights up 4 key RGB LEDs rather than the 27 key LEDs and 4 backlight LEDs.

**Comment by NachoxMacho** [comment]
> @NachoxMacho Does your Montex V1 have full per-key RGB lighting? I wonder if I have a V2 because your build only lights up 4 key RGB LEDs rather than the 27 key LEDs and 4 backlight LEDs.

No, my Montex V1 only has 4 backlight LEDs, and as far as I'm aware that's all the code supports at this point.

**Comment by IBNobody** [comment]
Good to know. I'll submit a V2 that supports the newer PCB. The V2 expanded
the LED underbody lighting to be the per key lighting, and increasing the 4
led define to 27 gave me full lighting.
