### ISSUE TITLE
Add the idobao montex as a Powered by QMK keyboard

### ISSUE THREAD

**Issue by IDOBAOKB** [qmk/qmk.fm_old#131]
Hello:
I'd be interested in having the montex as one of the keyboards that's supported by QMK.

**Comment by iso-hexane** [comment]
This thread might help: https://github.com/qmk/qmk.fm/issues/103#issuecomment-619425051

**Comment by IDOBAOKB** [comment]
get it ,thanks





Lewis Liu
ShenZhen IDOBAO E-commerce Limited.
Email: ***@***.*** 
phone# : 13686468936
409, building A1, newshangzhigu, Zhancheng community, Fuhai street, Bao'an District, Shenzhen
www.idobao.net
ε٩(๑> ₃ <)۶з…………………………

——  I am very happy to serve you and hope to help you solve your doubts.




— Thank you for watching, I wish you a happy life and good luck with you always. —
 
From: Zach White
Date: 2021-07-11 13:52
To: qmk/qmk.fm
CC: IDOBAOKB; Author
Subject: Re: [qmk/qmk.fm] Add the idobao montex as a Powered by QMK keyboard (#131)
Closed #131.
