### ISSUE TITLE
ID67 missing from the list

### ISSUE THREAD

**Issue by igorchu** [qmk/qmk.fm_old#133]
On IDOBAO website it states that it is QMK compatibile but I can't find qmk.fm for it.
https://www.idobao.net/products/idobao-id67-65-hot-swappable-mechanical-keyboard-kit-1

**Comment by noroadsleft** [comment]
Idobao doesn't publish source code or files from which source code can be generated. QMK largely depends on community members such as yourself to add support for these boards. This board will likely remain unsupported until source is contributed.

I realize this isn't a positive answer, but it's the reality.
