### ISSUE TITLE
[Bug] Missing Default Firmware .hex/.bin Files

### ISSUE THREAD

**Issue by yeedster** [qmk/qmk.fm_old#139]
### Describe the Bug

Tried to load in the .hex file for the new momoka_ergo and qmktoolbox cannot find the file.  Going on the qmkconfigurator allows me to grab a default / customized .hex file.

**Comment by noroadsleft** [comment]
There's probably a lot of default keymaps that are missing or not current. We used to deploy them to the website through Travis CI, but Travis CI is no longer available to us, so these aren't getting deployed automatically anymore and we haven't yet worked out a way to do that.

For now, have this. Remove the `.txt` from the filename and flash it; it's freshly compiled.

[momoka_ergo_default.hex.txt](https://github.com/qmk/qmk.fm/files/7100793/momoka_ergo_default.hex.txt)
