### ISSUE TITLE
[Bug] *** No .hex file found, trying https://qmk.fm/compiled/montex_default.bin     Something went wrong when trying to get the default keymap file.

### ISSUE THREAD

**Issue by Quiksilve83** [qmk/qmk.fm_old#140]
### Describe the Bug

Howdy

I'm always getting this error msg when trying to flash my idobao montex numpad firmware.
![error message1](https://user-images.githubusercontent.com/90487534/132932006-b8e8c9d0-82d6-462b-9f84-c1fb9601467f.png)

I've check on the website there is a missing montex hex file
![Montex file missing](https://user-images.githubusercontent.com/90487534/132932044-37f785bf-5837-405d-8ef2-e7027425186c.png)

Please assist me to help so that I can remap my montex numpad thank you

**Comment by noroadsleft** [comment]
Sorry for the slow response; you should ignore the "Keyboard from qmk.fm" section in QMK Toolbox. Provide the local file as you have done, put the board into bootloader mode, then click the Flash button in Toolbox.

Regarding the missing hex file from qmk.fm, we lost access to the tooling that we were using to put these files on the site. I actually generated the default firmware files manually a couple of weeks ago, but then I ran into a roadblock with generating the page that lists the firmware files. We still don't have a good solution for this, unfortunately.

**Comment by mix3d** [comment]
Is there any way to at least change the website to hide the keyboards section on the website on qmk.fm? Or even update this repo's description that said functionality is broken?

**Comment by waffletower** [comment]
I assumed that `No .hex file found` was my issue.  Ignoring `Keyboard from qmk.fm` section doesn't improve matters.  I load  the firmware and puty my GMMK PRro ansi into bootloader mode and the `Flash` button remains grayed out.

**Comment by noroadsleft** [comment]
> Is there any way to at least change the website to hide the keyboards section on the website on qmk.fm? Or even update this repo's description that said functionality is broken?

@mix3d I actually updated the page and the firmware files manually a few days ago (#152). The automation is broken but the site can still be updated.

> I assumed that `No .hex file found` was my issue. Ignoring `Keyboard from qmk.fm` section doesn't improve matters. I load the firmware and puty my GMMK PRro ansi into bootloader mode and the `Flash` button remains grayed out.

@waffletower This sounds like an issue more appropriate for the `qmk/qmk_firmware` repository. A screenshot of QMK Toolbox (or a copy/paste of its terminal output) would be good.
