### ISSUE TITLE
System76 Launch keyboard use QMK by default

### ISSUE THREAD

**Issue by reesericci** [qmk/qmk.fm_old#141]
### Information

- [X] None of the other issue templates apply

### Description

The System76 Launch Keyboard [https://system76.com/accessories/launch](https://system76.com/accessories/launch) uses QMK by default and it says on the website to file an issue if a keyboard uses QMK by default to get listed.

**Comment by tzarc** [comment]
This has not been upstreamed into QMK. I'm not sure what the status is, in that respect.
@qmk/directors what's the status in this scenario?

**Comment by reesericci** [comment]
Yeah its a fork https://github.com/system76/qmk_firmware

**Comment by skullydazed** [comment]
Once it's been submitted to qmk_firmware it will be listed on the keyboards page. We don't list boards that haven't been contributed to us.
