### ISSUE TITLE
[Feature Request] K617 fizz

### ISSUE THREAD

**Issue by mahmouddsamirr** [qmk/qmk.fm_old#155]
### Description

would there be any future support for BYK916 (a rebranded of Sinowealth SH68F90) chip? I saw someone on reddit said that the problem with this chip is that there is no data sheet for it but I found one in a Chinese site. would this help you support keyboards with this chip? i belive its 8bit with 64k storage

**Comment by mahmouddsamirr** [comment]
> ### Description
> would there be any future support for BYK916 (a rebranded of Sinowealth SH68F90) chip? I saw someone on reddit said that the problem with this chip is that there is no data sheet for it but I found one in a Chinese site. would this help you support keyboards with this chip? i belive its 8bit with 64k storage

redragon k617 (my keyboard with this chip) already have a backup firmware from its vendor

**Comment by r3d5ky** [comment]
[I found some source code](https://github.com/szhj123/mouse_bat32g157/tree/master/document/K916%20998版NEW%20三模%20B10.00) for this MCU, looks like it is a complete keyboard project (maybe leaked or accidentally published from some of the vendors), hope that helps with reverse-engineering and understanding how these MCUs work.

**Comment by tzarc** [comment]
Feel free to open a PR against qmk_firmware once you've done the legwork.

**Comment by hansfbaier** [comment]
@mahmouddsamirr Can you post the datasheet and the backup firmware?
