### ISSUE TITLE
Support for Keychron K8 Pro QMK or Q3

### ISSUE THREAD

**Issue by Java-Fish** [qmk/qmk.fm_old#156]
### Description

Hi,

With the new K8 and the Q3 keyboard from Keychron, there are now 80% keyboards with QMK firmware from this manufacturer, but I can't find a suitable layout for them.

https://www.keychron.com/products/keychron-k8-pro-qmk-via-wireless-mechanical-keyboard

https://www.keychron.com/products/keychron-q3-qmk-custom-mechanical-keyboard

**Comment by albocc** [comment]
Any update on this? Is there a way to use a different layout for the Q3?

**Comment by hausteen** [comment]
I also would really like to have the Q3 added please! At least to the online configurator please!

**Comment by albocc** [comment]
@zvecr : Is support for both keyboards not planned? This is a bit surprising, since the Q3 is marketed as a QMK-compatible keyboard.

**Comment by tzarc** [comment]
Q3 is already in the qmk_firmware repository, K8 Pro is in the pipeline.

It's more that this issue shouldn't be present in this repository -- Z was doing cleanup.

**Comment by leemlller** [comment]
Any ETA for K8PRO?

**Comment by seanparmelee** [comment]
FWIW, keychron has the source code for the K Pro series in its QMK fork: https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron
