### ISSUE TITLE
[Feature Request] Not able to change the configuration of my Ducky one 2 SF

### ISSUE THREAD

**Issue by stutteroid** [qmk/qmk.fm_old#173]
### Description

Not able to change the configuration of my Ducky one 2 SF keyboard although it is listed in the layout edit tab, but I am not able to enter the flashing state in the configurator tool

**Comment by noroadsleft** [comment]
1. This sounds like a QMK Configurator issue, but this repository doesn't have anything to do with Configurator. [QMK Configurator's repository is here.](https://github.com/qmk/qmk_configurator).
2. QMK Configurator doesn't flash keyboards - it only compiles firmware that can then be flashed with something like QMK Toolbox.
3. The Ducky One 2 SF's controller isn't supported by QMK Toolbox. You'd need to install `nuvoton-isp` or `nu-isp-cli` as described in [the keyboard's readme](https://github.com/qmk/qmk_firmware/tree/e0c00c35ce195dc0ab3f729235b9490dc69592ec/keyboards/ducky/one2sf/1967st#flashing-the-firmware).
