### ISSUE TITLE
Missing device in the list with the supported keyboards

### ISSUE THREAD

**Issue by dariox86** [qmk/qmk.fm_old#176]
### Describe the Bug

At https://qmk.fm/keyboards/ there is ducky/one2mini/1861st while ducky/one2sf/1967st is missing even though there is a [dedicated path on GitHub](https://github.com/qmk/qmk_firmware/tree/master/keyboards/ducky/one2sf/1967st).

**Comment by zvecr** [comment]
That page is no longer updated and is due to be removed, #142.
