### ISSUE TITLE
[Bug] Recent changes page has the last change from 2019, it's 2024

### ISSUE THREAD

**Issue by C0rn3j** [qmk/qmk.fm_old#181]
### Describe the Bug

https://qmk.fm/changes/

![image](https://github.com/qmk/qmk.fm/assets/1641362/1a830e28-10f9-49fc-95e0-809d5f0db504)

**Comment by zvecr** [comment]
Major changes to qmk_firmware are now detailed at <https://docs.qmk.fm/breaking_changes_history>.

**Comment by C0rn3j** [comment]
This issue should not be closed as long as the dead page is prominently featured in the main qmk.fm page.

**Comment by zvecr** [comment]
I should add that the site is being completely replaced.

Rather than ignore the issue completely, I figured I would at least give some up to date context before it becomes irrelevant.
