### ISSUE TITLE
Encoder page link in features page

### ISSUE THREAD

**Issue by cafarella** [qmk/qmk.fm_old#27]
The encoders page [https://docs.qmk.fm/#/feature_encoders](url) has not been linked properly to the features page [https://docs.qmk.fm/#/features](url). Can someone please update the features page with a link to the encoders page.

**Comment by drashna** [comment]
The Docs site is actually managed from the QMK FIrmware repo, not from here. 

To fix that, you'd want to edit this page: https://github.com/qmk/qmk_firmware/blob/master/docs/features.md

**Comment by cafarella** [comment]
Thanks, will do
