### ISSUE TITLE
Include Proton C damage warning in temporary page and in final docs

### ISSUE THREAD

**Issue by derywat** [qmk/qmk.fm_old#30]
Some of the PCBs compatible with Pro Micro have VCC and RAW pins conected (shorted) on the pcb (found one when converting Gherkin keyboard). Using the Proton C will short 5V power from USB and regulated 3.3V which is connected directly to MCU. Shorting those pins will likely damage the MCU on Proton C.

Please include the warning and information about leaving 5V pin of Proton C unconnected if a pcb has shorted those pins on the temporary page regarding Proton C. Please include this in the final documentation also.

**Comment by drashna** [comment]
Is that just the gherkin?  Do you know if any other boards are doing this?

**Comment by derywat** [comment]
> Is that just the gherkin? Do you know if any other boards are doing this?

I didn't check the other boards so I can't tell. Now I have only Gherkin and Contra that use Pro Micro. Gherkin has this issue in rev 1.0 and 1.1. The Contra is powered from VCC pin and everything works very well with Proton C.
I guess, that most of the boards take power from VCC/3.3V pin.

I found one more issue with 5V pin - if the board takes power from it (and not from VCC/3.3V), there may be a problem with MCU pins that are not 5V tolerant. If the board uses pins that are not 5V tolerant, it may source current from 5V to those pins (e.g. driving single leds without mosfet or driving unused pins high by external pull-up). It is not as dangerous as shorted pins, but should be checked before using proton C with board like this.

I think, that the docs should suggest to not connect 5V pin to the board at all, just to stay safe, and use 5V only when the board needs 5V and after checking if it's safe.
