### ISSUE TITLE
Getting XD60/64 V3 Underglow Working

### ISSUE THREAD

**Issue by Thorhian** [qmk/qmk.fm_old#36]
Hello Everyone,
A while back I built a keyboard using the XD60/64 PCB and I installed the QMK firmware onto it relatively easy with just a couple of hiccups. The keyboard matrix works just fine and I love being able to customize the firmware so much, but I cannot get the RGB underglow working on this keyboard. It worked just fine when I bought it still had the stock TMK firmware, but since then I haven't been able to get it working. After some digging in the config.h files for this board and my layout, it seems that the current layout for the xd60 in the repository is for the v2 version of the board, and I have the v3 version. After pulling up a diagram of the pinouts of the atmega 32u4 I tried specifying some different pins that weren't being used to no success. Occasionally the keyboard stops working if I wiggle the USB-C connector when the board is outside of its case and the one of the underglow LED's will flash green when this happens. Simply plugging the board back in solves that issue, but I know that at least that LED isn't burnt out. 

I guess my main question is how should I go about solving this. I'm not sure how I would get a board schematic. I'm not the most experienced dealing with microcontrollers and C but I have done a little bit. I wish I had a better multimeter and setup to probe around the board to see where everything is going but since it's multilayered I haven't had much luck with my limited skills.

**Comment by Thorhian** [comment]
So I just realized I posted this on the repo for QMK's website, should I close this and open an issue in the actual firmware repo?

**Comment by drashna** [comment]
Yeah, if you could

**Comment by Thorhian** [comment]
Done!
