### ISSUE TITLE
Satan GH60 RevCHN

### ISSUE THREAD

**Issue by johnfwhitmore** [qmk/qmk.fm_old#38]
I'm sure this has been asked before but I'm struggling to find any information. I'm new to keyboards and assumed that the GH60 was supported by QMK_Firmware but now I have the board and soldered it up it appears not. 
I'm not new to embedded programming so I guess if I can make sense of the schematic and the build process then I could port the firmware?
So no this ain't an issue but didn't see where else to question the project.

**Comment by drashna** [comment]
the qmk firmware repo would be more appropriate to that. 

But that said, there is the GH60, and the Satan board. Both are for the same layout/formfactor, so you may want to check which is correct.

**Comment by noroadsleft** [comment]
@johnfwhitmore 

Just looked into this. Your board is already in QMK, under the name [`satan`](https://github.com/qmk/qmk_firmware/tree/master/keyboards/satan).

There are [some changes coming to its codebase](https://github.com/qmk/qmk_firmware/pull/5264), but the firmware AFAIK is fully functional.

**Comment by johnfwhitmore** [comment]
Sorry I put this in the wrong place, should have been in qmk_firmware.

Apologies
