### ISSUE TITLE
There are identical files only differing in capitalisation. This doesn't work on windows

### ISSUE THREAD

**Issue by Duckle29** [qmk/qmk.fm_old#41]
I'm in the process of adding a page for a keyboard, and git has complained about some "duplicate" files.

in particular:

- compiled/handwired_CMD60_default.hex and compiled/handwired_cmd60_default.hex
- compiled/handwired_MS_sculpt_mobile_default.hex and compiled/handwired_ms_sculpt_mobile_default.hex

It seems the lower-case files are much newer, and it probably isn't even intentional to have two copies around. But I don't know that for sure :)

**Comment by drashna** [comment]
Ah, yeah, we need a cleanup script for this, I think. 

Specifically, those boards were refactored to be lower case only.    

I can delete them manually, but that won't stop the issue from happening again in the future.

**Comment by drashna** [comment]
If you update/reclone/reset to head, it should fix the issue now
