### ISSUE TITLE
flabbergast keyboard

### ISSUE THREAD

**Issue by vexseer** [qmk/qmk.fm_old#7]
hi .. could you help me add the flabbergast keyboard to qmk .. here are the files from tmk
[kb45p.zip](https://github.com/qmk/qmk.fm/files/1556756/kb45p.zip)

**Comment by drashna** [comment]
You'd want to add this to the QMK Firmware repo, actually.  

The keyboard list is generated from that repo, so adding it there will add it here. 

Also, just in case @mechmerlin?

**Comment by mechmerlin** [comment]
Sure, this needs to be filed in qmk_firmware actually, but I can help with the moving the flabbergast into QMK.

**Comment by vexseer** [comment]
thanks very much ..
