### ISSUE TITLE
<details> not displaying properly in beta.docs

### ISSUE THREAD

**Issue by Gouty** [qmk/qmk.fm_old#92]
I updated the handwire guide (https://github.com/qmk/qmk_firmware/blob/master/docs/hand_wire.md) and it displays great in regular https://docs.qmk.fm/#/hand_wire but does not display properly in https://beta.docs.qmk.fm/for-makers-and-modders/hand_wire

The areas that do not display correctly are within `<details>` tags

**Comment by drashna** [comment]
To be fair, beta.docs.qmk.fm needs to be deprecated.

**Comment by tzarc** [comment]
> To be fair, beta.docs.qmk.fm needs to be deprecated.

And has been.
